### ISSUE TITLE
Про тесты

### ISSUE THREAD

**Issue by K1ola** [go-park-mail-ru/2022_2_VDonate#18]
- Мне не понравился тест TestServer_Start по след причинам

    1. начинка теста ничего не проверяет сама по себе, ее можно спокойно заменить на if в самом приложении. Данный тест по сути проверяет, не забыли ли вы положить нужный конфиг в сервис. Это нужно проверять на **старте** приложения, а не на прогоне тестов
    2. при тестировании методов, которые работают с ос, нужно работать более осторожно, там своя специфика в отличие от тестирования ваших ручек или бизнес логики. Работу с ОС в тестах вы не сможете обеспечить на 100: надежно в рамках веб-приложения, поэтому лучше тестами максимально покрывать бизнес логику и интеграционное взаимодействие с другими сервисами, а работу с ос проверять в самом приложении

- В табличных тестах использовать **уникальные говорящие имена**. Это поможет, когда у вас будет 100+ тестов и какой-нибудь один рухнет.

**Comment by zeronethunter** [comment]
We are closing the issue because we have fixed the remarks :smile:
